### ISSUE TITLE
`packageDeps.install()` causes exception "querySelector is not a function"

### ISSUE THREAD

**Issue by Shchvova** [steelbrain/package-deps#108]
Error when trying to install dependency. Only thing I have in code, is in `package.json`:
```json
  "dependencies": {
    "atom-package-deps": "^3.0.0"
  },
  "package-deps": [
    "language-lua"
  ]
```
And in `main.coffee`:
```
module.exports =
    config:
      includeArguments:
        type: 'boolean'
        default: true
    activate: ->
        packageDeps.install()
        .then ->
          provider.loadCompletions()
```
This causes exception:
```Uncaught TypeError: this.element.querySelector is not a function
/Users/vlad/.atom/packages/autocomplete-corona/node_modules/atom-package-deps/lib/view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/Users/vlad/.atom/packages/autocomplete-corona/node_modules/atom-package-deps/lib/view.js:41:36)
    at /Users/vlad/.atom/packages/autocomplete-corona/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/Users/vlad/.atom/packages/autocomplete-corona/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```
![image](https://user-images.githubusercontent.com/130387/29675968-c801d1c4-88c4-11e7-85fd-8aa59d0f4418.png)

Steps to reproduce:
1. delete `language-lua`
2. Install "autocomplete-corona" from Atom package GUI

**Comment by Arcanemagus** [comment]
This was fixed _long_ ago, please update to using the currently released version of `atom-package-deps` 😉.

**Comment by Arcanemagus** [comment]
Also note that although it's supported to not pass a package name into `install`, you can save ~12 ms off the activation time by manually doing so.
