### ISSUE TITLE
Can't bring up the integration

### ISSUE THREAD

**Issue by pschaumburg** [steelbrain/package-deps#123]
Hey there,

I'm currently facing an issue with my integration. 

This is my package: https://github.com/sous-chefs/language-chef/tree/feature/dependency-inspec
The package.json: https://github.com/sous-chefs/language-chef/blob/feature/dependency-inspec/package.json
And the main.js, which is loaded: https://github.com/sous-chefs/language-chef/blob/feature/dependency-inspec/lib/main.js

I've tried different things, but did not mentioned out anyone to work. I'm always getting an error, which is just showing up for a milisecond or so. 

Could you just give me hint, what I'm doing wrong right now?

Best regards,
Patrick

**Comment by steelbrain** [comment]
Hi @pschaumburg 

The code is not working because you are overriding one of your exports with the other. Your `main.js` could be made into this to work

```js
'use babel';

import chefProviderRecipes from './chef-provider-recipes';
import chefProviderMetadata from './chef-provider-metadata';

export function activate() {
  require('atom-package-deps').install('language-chef')
    .then(function() {
      console.log('All dependencies installed, good to go')
    })
}

export function getProvider() {
  return [
    chefProviderMetadata,
    chefProviderRecipes
  ];
}
```

**Comment by pschaumburg** [comment]
Hi steelbrain,

Thank you for your fast response. I'm sorry for this (it is my first js experience 🗡 ) 
I've changed the main.js as mentioned, but receiving this:


Failed to activate the language-chef package
Cannot find module 'atom-package-deps'

```
Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/Users/pstecracer/Documents/Repositories/language-chef/lib/main.js:7:3)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

**Comment by steelbrain** [comment]
@pschaumburg It appears that while you've added the dependency in `dependency-inspec` branch https://github.com/sous-chefs/language-chef/blob/aa9beaeabfb52a192e469b59caadc9f49c712294/package.json#L25, you have not added it in the master branch https://github.com/sous-chefs/language-chef/blob/186d04198c5af447aaa580c9855edb20c6f5655d/package.json#L24

So you may wanna do a `npm i atom-package-deps` in the master branch as well :)

**Comment by pschaumburg** [comment]
Sorry, I don't understand this behaviour :/
I thought, that the dependency within the package.json is enough to install the npm package automatically. Or am i wrong? 

But I also have done your advise:
I just ran `npm i atom-package-deps` and it installed your package. After a restart of Atom, the popup came up and i could install language-inspec.
