### ISSUE TITLE
Installing linter-eslint fails from uncaught exception in main.js

### ISSUE THREAD

**Issue by jonboiser** [steelbrain/package-deps#30]
Clean install of linter-eslint@5.2.1, atom@1.2.3, linter@1.11.2 on OS X Yosemite

An error is thrown from the `atom-package-deps/lib/main.js` at https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L15, which causes the rest of the package to fail.

In the debugger, it seems that the call `require('callsite')()` returns the following error string

```
"Error
    at Object.eval (eval at evaluate (unknown source), <anonymous>:1:20)
    at Object.InjectedScript._evaluateOn (<anonymous>:904:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:963:21)
    at Object.install (/Users/jonathan/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/main.js:15:5)
    at Object.activate (/Users/jonathan/.atom/packages/linter-eslint/lib/main.js:53:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26"
```

which then results in the expression `require('callsite')()[1].getFileName()` to throw a 'not a function error', since `require('callsite')()[1]` is simply the character "E".

**Comment by Arcanemagus** [comment]
I'm seeing this on Windows as well, so it's not just an OS X issue.

**Comment by steelbrain** [comment]
Ouch, I wonder why it's working perfectly fine for me on Linux

**Comment by steelbrain** [comment]
I'll test this on a windows machine shortly and see if the results differ

**Comment by steelbrain** [comment]
I am able to repro this on a windows machine, investigating

**Comment by steelbrain** [comment]
Turns out the callsite module isn't cross-platform, I'll write an alternative which is
